[project]
name = "extractor"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "langextract[openai]>=1.0.8",
    "streamlit>=1.48.1",
    "streamlit-agraph>=0.0.45",
]
